spring.application.name=demo

# To expose on LAN
#server.address=0.0.0.0

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:server.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
